// <auto-generated />
using System;
using CalorieTrackingApp.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CalorieTrackingApp.DAL.Migrations
{
    [DbContext(typeof(CalorieDbContext))]
    [Migration("20241012173138_AllSeedDataAndFluentApiSettings")]
    partial class AllSeedDataAndFluentApiSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CalorieTrackingApp.DAL.Entities.Concrete.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminName")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DataStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdminName = "admin",
                            CreatedDate = new DateTime(2024, 10, 10, 21, 34, 51, 585, DateTimeKind.Local).AddTicks(9444),
                            DataStatus = 0,
                            Name = "Admin_Name",
                            Password = "admin123",
                            Surname = "Admin_Surname"
                        });
                });

            modelBuilder.Entity("CalorieTrackingApp.DAL.Entities.Concrete.Beverage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BeverageCalorie")
                        .HasColumnType("decimal(7, 2)");

                    b.Property<int>("BeverageCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("BeverageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DataStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PortionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BeverageCategoryId");

                    b.HasIndex("PortionId");

                    b.ToTable("Beverages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BeverageCalorie = 0m,
                            BeverageCategoryId = 3,
                            BeverageName = "Su",
                            CreatedDate = new DateTime(2024, 10, 10, 21, 34, 51, 585, DateTimeKind.Local).AddTicks(9444),
                            DataStatus = 0,
                            PortionId = 5
                        },
                        new
                        {
                            Id = 2,
                            BeverageCalorie = 2m,
                            BeverageCategoryId = 1,
                            BeverageName = "Sade Türk Kahvesi",
                            CreatedDate = new DateTime(2024, 10, 10, 21, 34, 51, 585, DateTimeKind.Local).AddTicks(9444),
                            DataStatus = 0,
                            PortionId = 4
                        },
                        new
                        {
                            Id = 3,
                            BeverageCalorie = 15m,
                            BeverageCategoryId = 1,
                            BeverageName = "Orta Türk Kahvesi",
                            CreatedDate = new DateTime(2024, 10, 10, 21, 34, 51, 585, DateTimeKind.Local).AddTicks(9444),
                            DataStatus = 0,
                            PortionId = 4
                        },
                        new
                        {
                            Id = 4,
                            BeverageCalorie = 25m,
                            BeverageCategoryId = 1,
                            BeverageName = "Şekerli Türk Kahvesi",
                            CreatedDate = new DateTime(2024, 10, 10, 21, 34, 51, 585, DateTimeKind.Local).AddTicks(9444),
                            DataStatus = 0,
                            PortionId = 4
                        },
                        new
                        {
                            Id = 5,
                            BeverageCalorie = 149m,
                            BeverageCategoryId = 2,
                            BeverageName = "Kola",
                            CreatedDate = new DateTime(2024, 10, 10, 21, 34, 51, 585, DateTimeKind.Local).AddTicks(9444),
                            DataStatus = 0,
                            PortionId = 6
                        },
                        new
                        {
                            Id = 6,
                            BeverageCalorie = 1m,
                            BeverageCategoryId = 2,
                            BeverageName = "Light veya Zero Kola",
                            CreatedDate = new DateTime(2024, 10, 10, 21, 34, 51, 585, DateTimeKind.Local).AddTicks(9444),
                            DataStatus = 0,
                            PortionId = 6
                        },
                        new
                        {
                            Id = 7,
                            BeverageCalorie = 60m,
                            BeverageCategoryId = 2,
                            BeverageName = "Soğuk Çay",
                            CreatedDate = new DateTime(2024, 10, 10, 21, 34, 51, 585, DateTimeKind.Local).AddTicks(9444),
                            DataStatus = 0,
                            PortionId = 6
                        },
                        new
                        {
                            Id = 8,
                            BeverageCalorie = 10m,
                            BeverageCategoryId = 2,
                            BeverageName = "Light veya Zero Soğuk Çay",
                            CreatedDate = new DateTime(2024, 10, 10, 21, 34, 51, 585, DateTimeKind.Local).AddTicks(9444),
                            DataStatus = 0,
                            PortionId = 6
                        },
                        new
                        {
                            Id = 9,
                            BeverageCalorie = 40m,
                            BeverageCategoryId = 2,
                            BeverageName = "Şalgam(Acılı)",
                            CreatedDate = new DateTime(2024, 10, 10, 21, 34, 51, 585, DateTimeKind.Local).AddTicks(9444),
                            DataStatus = 0,
                            PortionId = 5
                        });
                });

            modelBuilder.Entity("CalorieTrackingApp.DAL.Entities.Concrete.BeverageCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BeverageCategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DataStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("BeverageCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BeverageCategoryName = "Sıcak İçecek",
                            CreatedDate = new DateTime(2024, 10, 10, 21, 34, 51, 585, DateTimeKind.Local).AddTicks(9444),
                            DataStatus = 0
                        },
                        new
                        {
                            Id = 2,
                            BeverageCategoryName = "Soğuk İçecek",
                            CreatedDate = new DateTime(2024, 10, 10, 21, 34, 51, 585, DateTimeKind.Local).AddTicks(9444),
                            DataStatus = 0
                        },
                        new
                        {
                            Id = 3,
                            BeverageCategoryName = "Su",
                            CreatedDate = new DateTime(2024, 10, 10, 21, 34, 51, 585, DateTimeKind.Local).AddTicks(9444),
                            DataStatus = 0
                        });
                });

            modelBuilder.Entity("CalorieTrackingApp.DAL.Entities.Concrete.DailyUserRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BeverageId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DataStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.Property<int>("MealId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PortionId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("RecordDate")
                        .HasColumnType("date");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BeverageId");

                    b.HasIndex("FoodId");

                    b.HasIndex("MealId");

                    b.HasIndex("PortionId");

                    b.HasIndex("UserId");

                    b.ToTable("DailyUserRecord");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BeverageId = 2,
                            CreatedDate = new DateTime(2024, 10, 10, 21, 34, 51, 585, DateTimeKind.Local).AddTicks(9444),
                            DataStatus = 0,
                            FoodId = 16,
                            MealId = 1,
                            PortionId = 3,
                            RecordDate = new DateOnly(2024, 10, 10),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            BeverageId = 9,
                            CreatedDate = new DateTime(2024, 10, 10, 21, 34, 51, 585, DateTimeKind.Local).AddTicks(9444),
                            DataStatus = 0,
                            FoodId = 10,
                            MealId = 2,
                            PortionId = 1,
                            RecordDate = new DateOnly(2024, 10, 10),
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            BeverageId = 7,
                            CreatedDate = new DateTime(2024, 10, 10, 21, 34, 51, 585, DateTimeKind.Local).AddTicks(9444),
                            DataStatus = 0,
                            FoodId = 12,
                            MealId = 4,
                            PortionId = 1,
                            RecordDate = new DateOnly(2024, 10, 10),
                            UserId = 3
                        });
                });

            modelBuilder.Entity("CalorieTrackingApp.DAL.Entities.Concrete.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DataStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FoodCalorie")
                        .HasColumnType("decimal(7, 2)");

                    b.Property<int>("FoodCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PortionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FoodCategoryId");

                    b.HasIndex("PortionId");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 10, 10, 21, 34, 51, 585, DateTimeKind.Local).AddTicks(9444),
                            DataStatus = 0,
                            FoodCalorie = 6m,
                            FoodCategoryId = 1,
                            FoodName = "Zeytin",
                            PortionId = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 10, 10, 21, 34, 51, 585, DateTimeKind.Local).AddTicks(9444),
                            DataStatus = 0,
                            FoodCalorie = 85m,
                            FoodCategoryId = 1,
                            FoodName = "Beyaz Peynir",
                            PortionId = 3
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 10, 10, 21, 34, 51, 585, DateTimeKind.Local).AddTicks(9444),
                            DataStatus = 0,
                            FoodCalorie = 17m,
                            FoodCategoryId = 1,
                            FoodName = "İncir Reçeli",
                            PortionId = 7
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 10, 10, 21, 34, 51, 585, DateTimeKind.Local).AddTicks(9444),
                            DataStatus = 0,
                            FoodCalorie = 55m,
                            FoodCategoryId = 1,
                            FoodName = "Tahin Pekmez",
                            PortionId = 7
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 10, 10, 21, 34, 51, 585, DateTimeKind.Local).AddTicks(9444),
                            DataStatus = 0,
                            FoodCalorie = 90m,
                            FoodCategoryId = 2,
                            FoodName = "Mercimek Çorba",
                            PortionId = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 10, 10, 21, 34, 51, 585, DateTimeKind.Local).AddTicks(9444),
                            DataStatus = 0,
                            FoodCalorie = 80m,
                            FoodCategoryId = 2,
                            FoodName = "Ezogelin Çorba",
                            PortionId = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2024, 10, 10, 21, 34, 51, 585, DateTimeKind.Local).AddTicks(9444),
                            DataStatus = 0,
                            FoodCalorie = 50m,
                            FoodCategoryId = 2,
                            FoodName = "Domates Çorba",
                            PortionId = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2024, 10, 10, 21, 34, 51, 585, DateTimeKind.Local).AddTicks(9444),
                            DataStatus = 0,
                            FoodCalorie = 35m,
                            FoodCategoryId = 3,
                            FoodName = "Mevsim Salata",
                            PortionId = 1
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2024, 10, 10, 21, 34, 51, 585, DateTimeKind.Local).AddTicks(9444),
                            DataStatus = 0,
                            FoodCalorie = 55m,
                            FoodCategoryId = 3,
                            FoodName = "Çoban Salata",
                            PortionId = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2024, 10, 10, 21, 34, 51, 585, DateTimeKind.Local).AddTicks(9444),
                            DataStatus = 0,
                            FoodCalorie = 300m,
                            FoodCategoryId = 4,
                            FoodName = "Adana Kebap",
                            PortionId = 1
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2024, 10, 10, 21, 34, 51, 585, DateTimeKind.Local).AddTicks(9444),
                            DataStatus = 0,
                            FoodCalorie = 100m,
                            FoodCategoryId = 4,
                            FoodName = "Zeytinyağlı Kereviz",
                            PortionId = 1
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2024, 10, 10, 21, 34, 51, 585, DateTimeKind.Local).AddTicks(9444),
                            DataStatus = 0,
                            FoodCalorie = 400m,
                            FoodCategoryId = 4,
                            FoodName = "Kayseri Yağlaması",
                            PortionId = 1
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2024, 10, 10, 21, 34, 51, 585, DateTimeKind.Local).AddTicks(9444),
                            DataStatus = 0,
                            FoodCalorie = 250m,
                            FoodCategoryId = 5,
                            FoodName = "Fırın Makarna",
                            PortionId = 1
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2024, 10, 10, 21, 34, 51, 585, DateTimeKind.Local).AddTicks(9444),
                            DataStatus = 0,
                            FoodCalorie = 350m,
                            FoodCategoryId = 6,
                            FoodName = "Patates Kızartması",
                            PortionId = 1
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2024, 10, 10, 21, 34, 51, 585, DateTimeKind.Local).AddTicks(9444),
                            DataStatus = 0,
                            FoodCalorie = 145m,
                            FoodCategoryId = 7,
                            FoodName = "Sütlaç",
                            PortionId = 1
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(2024, 10, 10, 21, 34, 51, 585, DateTimeKind.Local).AddTicks(9444),
                            DataStatus = 0,
                            FoodCalorie = 225m,
                            FoodCategoryId = 7,
                            FoodName = "Antep Fıstıklı Baklava",
                            PortionId = 3
                        },
                        new
                        {
                            Id = 17,
                            CreatedDate = new DateTime(2024, 10, 10, 21, 34, 51, 585, DateTimeKind.Local).AddTicks(9444),
                            DataStatus = 0,
                            FoodCalorie = 450m,
                            FoodCategoryId = 7,
                            FoodName = "Antep Fıstıklı Künefe",
                            PortionId = 1
                        });
                });

            modelBuilder.Entity("CalorieTrackingApp.DAL.Entities.Concrete.FoodCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DataStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FoodCategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("FoodCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 10, 10, 21, 34, 51, 585, DateTimeKind.Local).AddTicks(9444),
                            DataStatus = 0,
                            FoodCategoryName = "Kahvaltılık"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 10, 10, 21, 34, 51, 585, DateTimeKind.Local).AddTicks(9444),
                            DataStatus = 0,
                            FoodCategoryName = "Çorba"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 10, 10, 21, 34, 51, 585, DateTimeKind.Local).AddTicks(9444),
                            DataStatus = 0,
                            FoodCategoryName = "Salata"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 10, 10, 21, 34, 51, 585, DateTimeKind.Local).AddTicks(9444),
                            DataStatus = 0,
                            FoodCategoryName = "Ana Yemek"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 10, 10, 21, 34, 51, 585, DateTimeKind.Local).AddTicks(9444),
                            DataStatus = 0,
                            FoodCategoryName = "Makarna"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 10, 10, 21, 34, 51, 585, DateTimeKind.Local).AddTicks(9444),
                            DataStatus = 0,
                            FoodCategoryName = "Atıştırmalık"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2024, 10, 10, 21, 34, 51, 585, DateTimeKind.Local).AddTicks(9444),
                            DataStatus = 0,
                            FoodCategoryName = "Tatlı"
                        });
                });

            modelBuilder.Entity("CalorieTrackingApp.DAL.Entities.Concrete.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DataStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MealName")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Meals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 10, 10, 21, 34, 51, 585, DateTimeKind.Local).AddTicks(9444),
                            DataStatus = 0,
                            MealName = "Kahvaltı"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 10, 10, 21, 34, 51, 585, DateTimeKind.Local).AddTicks(9444),
                            DataStatus = 0,
                            MealName = "Öğle Yemeği"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 10, 10, 21, 34, 51, 585, DateTimeKind.Local).AddTicks(9444),
                            DataStatus = 0,
                            MealName = "Ara Öğün"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 10, 10, 21, 34, 51, 585, DateTimeKind.Local).AddTicks(9444),
                            DataStatus = 0,
                            MealName = "Akşam Yemeği"
                        });
                });

            modelBuilder.Entity("CalorieTrackingApp.DAL.Entities.Concrete.Portion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DataStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PortionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(7, 2)");

                    b.HasKey("Id");

                    b.ToTable("Portions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 10, 10, 21, 34, 51, 585, DateTimeKind.Local).AddTicks(9444),
                            DataStatus = 0,
                            PortionType = "Porsiyon(gr)",
                            ProductType = "Yiyecek",
                            Value = 125m
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 10, 10, 21, 34, 51, 585, DateTimeKind.Local).AddTicks(9444),
                            DataStatus = 0,
                            PortionType = "Adet(tane)",
                            ProductType = "Yiyecek",
                            Value = 1m
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 10, 10, 21, 34, 51, 585, DateTimeKind.Local).AddTicks(9444),
                            DataStatus = 0,
                            PortionType = "Dilim(tane)",
                            ProductType = "Yiyecek",
                            Value = 1m
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 10, 10, 21, 34, 51, 585, DateTimeKind.Local).AddTicks(9444),
                            DataStatus = 0,
                            PortionType = "Fincan(ml)",
                            ProductType = "İçecek",
                            Value = 100m
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 10, 10, 21, 34, 51, 585, DateTimeKind.Local).AddTicks(9444),
                            DataStatus = 0,
                            PortionType = "Kupa Bardak(ml)",
                            ProductType = "İçecek",
                            Value = 200m
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 10, 10, 21, 34, 51, 585, DateTimeKind.Local).AddTicks(9444),
                            DataStatus = 0,
                            PortionType = "Kutu(ml)",
                            ProductType = "İçecek",
                            Value = 330m
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2024, 10, 10, 21, 34, 51, 585, DateTimeKind.Local).AddTicks(9444),
                            DataStatus = 0,
                            PortionType = "Çay Kaşığı(gr)",
                            ProductType = "Yiyecek",
                            Value = 5m
                        });
                });

            modelBuilder.Entity("CalorieTrackingApp.DAL.Entities.Concrete.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DataStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("UserAgeGap")
                        .HasColumnType("int");

                    b.Property<int>("UserGoal")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 10, 10, 21, 34, 51, 585, DateTimeKind.Local).AddTicks(9444),
                            DataStatus = 0,
                            Email = "kgkalyoncu@mail.com",
                            Name = "Kazım Göksel",
                            Password = "kgk*user",
                            Surname = "Kalyoncu",
                            UserAgeGap = 4,
                            UserGoal = 2,
                            UserName = "kgkalyoncu@mail.com"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 10, 10, 21, 34, 51, 585, DateTimeKind.Local).AddTicks(9444),
                            DataStatus = 0,
                            Email = "alpceyhan@mail.com",
                            Name = "Alp",
                            Password = "alp*user",
                            Surname = "Ceyhan",
                            UserAgeGap = 4,
                            UserGoal = 2,
                            UserName = "alpceyhan@mail.com"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 10, 10, 21, 34, 51, 585, DateTimeKind.Local).AddTicks(9444),
                            DataStatus = 0,
                            Email = "alkinbayrak@mail.com",
                            Name = "Yahya Alkın",
                            Password = "ayb*user",
                            Surname = "Bayrak",
                            UserAgeGap = 3,
                            UserGoal = 3,
                            UserName = "alkinbayrak@mail.com"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 10, 10, 21, 34, 51, 585, DateTimeKind.Local).AddTicks(9444),
                            DataStatus = 0,
                            Email = "minelk@mail.com",
                            Name = "Minel",
                            Password = "minelk*user",
                            Surname = "Karakökçek",
                            UserAgeGap = 2,
                            UserGoal = 3,
                            UserName = "minelk@mail.com"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 10, 10, 21, 34, 51, 585, DateTimeKind.Local).AddTicks(9444),
                            DataStatus = 0,
                            Email = "efnan@mail.com",
                            Name = "Efnan",
                            Password = "efnan*user",
                            Surname = "Genç",
                            UserAgeGap = 1,
                            UserGoal = 3,
                            UserName = "efnan@mail.com"
                        });
                });

            modelBuilder.Entity("CalorieTrackingApp.DAL.ValueObject.TotalCalorie", b =>
                {
                    b.Property<string>("MealName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("RecordDate")
                        .HasColumnType("date");

                    b.Property<decimal>("TotalCalories")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.ToTable("TotalCalories");
                });

            modelBuilder.Entity("CalorieTrackingApp.DAL.ValueObject.UserMealBeverageCalorieGroup", b =>
                {
                    b.Property<string>("MealName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("RecordDate")
                        .HasColumnType("date");

                    b.Property<int>("TotalBeverageCalorie")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.ToTable("UserMealBeverageCalorieGroups");
                });

            modelBuilder.Entity("CalorieTrackingApp.DAL.ValueObject.UserMealDailyBeverageRecord", b =>
                {
                    b.Property<decimal>("BeverageCalorie")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BeverageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MealName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("RecordDate")
                        .HasColumnType("date");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("UserMealDailyBeverageRecords");
                });

            modelBuilder.Entity("CalorieTrackingApp.DAL.ValueObject.UserMealDailyFoodRecord", b =>
                {
                    b.Property<int>("FoodCalorie")
                        .HasColumnType("int");

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MealName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("RecordDate")
                        .HasColumnType("date");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable((string)null);

                    b.ToView("vwUserMealDailyFoodRecord", (string)null);
                });

            modelBuilder.Entity("CalorieTrackingApp.DAL.ValueObject.UserMealFoodCalorieGroup", b =>
                {
                    b.Property<string>("MealName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("RecordDate")
                        .HasColumnType("date");

                    b.Property<int>("TotalFoodCalorie")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.ToTable("UserMealFoodCalorieGroups");
                });

            modelBuilder.Entity("CalorieTrackingApp.DAL.Entities.Concrete.Beverage", b =>
                {
                    b.HasOne("CalorieTrackingApp.DAL.Entities.Concrete.BeverageCategory", "BeverageCategory")
                        .WithMany("Beverages")
                        .HasForeignKey("BeverageCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CalorieTrackingApp.DAL.Entities.Concrete.Portion", "Portion")
                        .WithMany("Beverages")
                        .HasForeignKey("PortionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BeverageCategory");

                    b.Navigation("Portion");
                });

            modelBuilder.Entity("CalorieTrackingApp.DAL.Entities.Concrete.DailyUserRecord", b =>
                {
                    b.HasOne("CalorieTrackingApp.DAL.Entities.Concrete.Beverage", "Beverages")
                        .WithMany("BeverageRecords")
                        .HasForeignKey("BeverageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CalorieTrackingApp.DAL.Entities.Concrete.Food", "Foods")
                        .WithMany("FoodRecords")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CalorieTrackingApp.DAL.Entities.Concrete.Meal", "Meals")
                        .WithMany("MealsRecords")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CalorieTrackingApp.DAL.Entities.Concrete.Portion", "Portions")
                        .WithMany("PortionRecords")
                        .HasForeignKey("PortionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CalorieTrackingApp.DAL.Entities.Concrete.User", "Users")
                        .WithMany("UserRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beverages");

                    b.Navigation("Foods");

                    b.Navigation("Meals");

                    b.Navigation("Portions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("CalorieTrackingApp.DAL.Entities.Concrete.Food", b =>
                {
                    b.HasOne("CalorieTrackingApp.DAL.Entities.Concrete.FoodCategory", "FoodCategory")
                        .WithMany("Foods")
                        .HasForeignKey("FoodCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CalorieTrackingApp.DAL.Entities.Concrete.Portion", "Portion")
                        .WithMany("Foods")
                        .HasForeignKey("PortionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("FoodCategory");

                    b.Navigation("Portion");
                });

            modelBuilder.Entity("CalorieTrackingApp.DAL.Entities.Concrete.Beverage", b =>
                {
                    b.Navigation("BeverageRecords");
                });

            modelBuilder.Entity("CalorieTrackingApp.DAL.Entities.Concrete.BeverageCategory", b =>
                {
                    b.Navigation("Beverages");
                });

            modelBuilder.Entity("CalorieTrackingApp.DAL.Entities.Concrete.Food", b =>
                {
                    b.Navigation("FoodRecords");
                });

            modelBuilder.Entity("CalorieTrackingApp.DAL.Entities.Concrete.FoodCategory", b =>
                {
                    b.Navigation("Foods");
                });

            modelBuilder.Entity("CalorieTrackingApp.DAL.Entities.Concrete.Meal", b =>
                {
                    b.Navigation("MealsRecords");
                });

            modelBuilder.Entity("CalorieTrackingApp.DAL.Entities.Concrete.Portion", b =>
                {
                    b.Navigation("Beverages");

                    b.Navigation("Foods");

                    b.Navigation("PortionRecords");
                });

            modelBuilder.Entity("CalorieTrackingApp.DAL.Entities.Concrete.User", b =>
                {
                    b.Navigation("UserRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
